export const FETCH_ARRAY_CAT_REQUEST = 'FETCH_ARRAY_CAT_REQUEST';
export const FETCH_ARRAY_CAT_SUCCESS = 'FETCH_ARRAY_CAT_SUCCESS';
export const FETCH_DELETE_ITEM = 'FETCH_DELETE_ITEM';
export const ADD_NEW_CAT = 'ADD_NEW_CAT'
export const FETCH_RETURN_ITEM = 'FETCH_RETURN_ITEM';
