export const FETCH_SELECTED_CAT_REQUEST = 'FETCH_SELECTED_CAT_REQUEST';
export const FETCH_SELECTED_CAT_SUCCESS = 'FETCH_SELECTED_CAT_SUCCESS';
export const FETCH_SELECTED_NEW_CAT = 'FETCH_SELECTED_NEW_CAT';